---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    git_root: "https://github.com/skamithi"
    tower_cli: "/home/skamithi/tower-cli/bin/tower-cli"
    tower_url: "https://192.168.121.89"
    tower_user: "admin"
    tower_pass: "tower"
    default_user_pass: "1q2w3e4r"
    dns_domainname: "example.com"
    tower_orgs:
      - name: testorg
      - name: testorg23
    tower_creds:
      - type: machine
        name: docker_test
        org: testorg
        fields:
          ssh_key_data: "{{ vault_docker_test_key }}"
          username: root
    tower_jobs:
      - name: first_run
        inv: mytestinv
        project: newrun
        play: demo.yml
        cred: docker_test
        team: testorg-admins


  roles:
    - tower-organization
    - tower-team
    - tower-user
    - tower-project
    - tower-credential
    - tower-inventory
    - tower-jobs
