---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    git_root: "https://github.com/skamithi"
    tower_cli: "/home/skamithi/tower-cli/bin/tower-cli"
    tower_action: create
    tower_url: "https://192.168.121.89"
    tower_user: "admin"
    tower_pass: "tower"
    tower_projects:
      - name: Test run
        descr: Test run
        url: https://github.com/linuxsimba/ansible-scale-testing
        branch: concurrency
        org: testorg
    tower_orgs:
      - name: testorg
      - name: testorg23
    tower_creds:
      - type: machine
        key: "{{ vault_docker_test_key }}"
        name: docker_test
        org: testorg
        username: root
    tower_inventories:
      - name: my inventory
        source:
          - name: engineering dept
            scm_url: "{{ git_root }}/inventory-script-test"
            script: inventory.py
  roles:
    - tower-organization
    - tower-project
    - tower-credential
