---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    git_root: "https://github.com/skamithi"
    tower_cli: "/home/skamithi/tower-cli/bin/tower-cli"
    tower_url: "https://192.168.121.89"
    tower_user: "admin"
    tower_pass: "tower"
    tower_projects:
      - name: testrun
        descr: Test run
        url: https://github.com/linuxsimba/ansible-scale-testing
        branch: concurrency
        org: testorg
      - name: project_for_docker_inv
        url: "{{ git_root }}/inventory-script-test"
        org: testorg

    tower_orgs:
      - name: testorg
      - name: testorg23
    tower_creds:
      - type: machine
        key: "{{ vault_docker_test_key }}"
        name: docker_test
        org: testorg
        username: root
    tower_inventories:
      - name: mytestinv
        org: testorg
        source:
          name: project_for_docker_inv
          script: inventory.py
    tower_jobs:
      - name: first_run
        inv: mytestinv
        project: testrun
        play: demo.yml
        cred: docker_test


  roles:
    - tower-organization
    - tower-project
    - tower-credential
    - tower-inventory
    - tower-jobs
