---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    git_root: "https://github.com/skamithi"
    tower_cli: "/home/skamithi/tower-cli/bin/tower-cli"
    tower_url: "https://192.168.121.89"
    tower_user: "admin"
    tower_pass: "tower"
    default_user_pass: "1q2w3e4r"
    dns_domainname: "example.com"
    tower_orgs: []
    tower_teams:  []
    tower_users: []
    tower_projects: []
    tower_cred_types: []
    tower_creds: []
    tower_inventories: []
    tower_jobs: []



  roles:
    - tower-organization
    - tower-team
    - tower-user
    - tower-project
    - tower-cred-type
    - tower-credential
    - tower-inventory
    - tower-jobs
