---
- name: get all job_template list data
  command: >
    {{ tower_cli }} job_template list
    -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
    -f json
  changed_when: false
  register: job_template_list_details

- name: get of installed list of job_templates names
  set_fact:
    installed_job_template_names: "{{ job_template_list_details.stdout|from_json|json_query('results[*].name') }}"

- name: list of desired job_templates
  set_fact:
    desired_job_template_list: "{{ tower_jobs|map(attribute='name')|list }}"

- name: job_templates_to_delete
  set_fact:
    delete_job_template_list: "{{ installed_job_template_names|difference(desired_job_template_list)}}"

- name: delete job_templates that are not defined
  command: >
    {{ tower_cli }} job_template delete
    -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
    --name {{ job_template|quote }}
    -f json
  register: job_template_status
  changed_when: '"\"changed\": true" in job_template_status.stdout'
  with_items: "{{ delete_job_template_list }}"
  loop_control:
    loop_var: job_template

