---
- name: set tower_jobs var if test_run is enabled
  set_fact:
    tower_jobs: "{{ lookup('template', 'test_jobs.j2') | from_yaml }}"
  when: test_run is defined
  tags:
    - job
    - create

- include_tasks: create.yml
  loop: "{{ tower_jobs }}"
  loop_control:
    loop_var: job
  tags:
    - job
    - create

- import_tasks: cleanup.yml
  tags:
    - job
    - cleanup

- import_tasks: run_job.yml
  tags:
    - never
    - run_job
