---
- name: "Create Organization"
  tower_organization:
    state: present
    tower_host: "{{ tower_url }}"
    tower_password: "{{ tower_pass }}"
    tower_username: "{{ tower_user }}"
    tower_verify_ssl: false
    name: "{{ org.name }}"
  loop: "{{ tower_orgs }}"
  loop_control:
    loop_var: org
