---
- name: "Create Organization - {{ tower_org }}"
  command: >
    {{ tower_cli }} organization modify
    -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
    --name {{ tower_org|quote }}
    -f json
    --create-on-missing
  register: org_status
  changed_when: '"\"changed\": true" in org_status.stdout'
