---
- name: add Default org to each tower list
  set_fact:
    tower_orgs: "{{ tower_orgs | union(default_org_list) }}"
  tags:
    - organization
    - cleanup

- import_tasks: create.yml
  tags:
    - organization
    - create

- import_tasks: cleanup.yml
  tags:
    - organization
    - cleanup
