tower_cred_types:
  - name: test_inventory_cred_type
    input_fields:
      - id: docker_host
        label: Docker Host

      - id: host_count
        secret: false
        label: Host Count
      - id: software_groups
        label: Software Groups
      - id: environment_groups
        label:  Environment Groups
    injector_fields:
      env:
        - "DOCKER_HOST"
        - "HOST_COUNT"
        - "SOFTWARE_GROUPS"
        - "ENVIRONMENT_GROUPS"
      extra_vars: []

tower_creds:
  - type: Machine
    name: docker_machine_creds
    org: testorg
    fields:
      ssh_key_data: "{{ vault_docker_test_key }}"
      username: root
  - type: test_inventory_cred_type
    name: docker_test_inventory
    org: testorg
    fields:
      docker_host: '192.168.121.1'
      host_count: 30
      software_groups: 'weblogic,java,tomcat'
      environment_groups: 'test,stage,prod'
