---
- include_tasks: create.yml
  loop: "{{ tower_inventories }}"
  loop_control:
    loop_var: inventory
  tags:
    - jobtemplate
    - create

- import_tasks: cleanup.yml
  tags:
    - jobtemplate
    - cleanup
