---
- name: get all cred list data
  command: >
    {{ tower_cli }} credential list
    -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
    -f json
  changed_when: false
  register: cred_list_details

- name: get of installed list of cred names
  set_fact:
    installed_cred_names: "{{ cred_list_details.stdout|from_json|json_query('results[*].name') }}"

- name: list of desired Creds
  set_fact:
    desired_cred_list: "{{ tower_creds|map(attribute='name')|list }}"

- name: credentials to delete
  set_fact:
    delete_cred_list: "{{ installed_cred_names|difference(desired_cred_list)}}"

- name: delete credentials that are not defined
  command: >
    {{ tower_cli }} credential delete
    -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
    --name {{ tower_cred|quote }}
    -f json
  register: cred_status
  changed_when: '"\"changed\": true" in cred_status.stdout'
  with_items: "{{ delete_cred_list }}"
  loop_control:
    loop_var: tower_cred
