---
- block:
  - name: Create a temporary file
    tempfile:
      state: file
      suffix: '.yaml'
    register: cred_input
    changed_when: false

  - name: create cred input file in the temporary file
    template:
      src: "cred_fields.j2"
      dest: "{{ cred_input.path }}"
    changed_when: false

  - name: "Create Credential"
    command: >
      {{ tower_cli }} credential create
      -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
      -f json --inputs @{{cred_input.path|quote}} --credential-type {{ cred.type}}
      --organization {{ cred.org|quote }} --name {{ cred.name|quote }}
    register: cred_status
    changed_when: '"\"changed\": true" in cred_status.stdout'

  - name: delete tempfile
    file:
      state: absent
      path: "{{ cred_input.path }}"
    changed_when: false
  tags:
    - credential
    - create


