---
- include_tasks: create.yml
  loop: "{{ tower_creds }}"
  loop_control:
    loop_var: cred
  tags:
    - credential
    - create

- import_tasks: cleanup.yml
  tags:
    - credential
    - cleanup
