---
- name: "Create Project"
  command: >
    {{ tower_cli }} project create
    -h {{ tower_url }} -u {{ tower_user }} -p {{ tower_pass }}
    --name {{ project.name|quote }}
    --scm-type {{ project.scm_type|default('git')|quote }}
    --scm-url {{ project.url|quote }}
    --scm-branch {{ project.branch|default('master')|quote }}
    --organization {{ project.org  }}
    --scm-update-on-launch true
    -f json
  register: project_status
  changed_when: '"\"changed\": true" in project_status.stdout'
  with_items: "{{ tower_projects }}"
  loop_control:
    loop_var: project
